### ISSUE TITLE
Getting some errors

### ISSUE THREAD

**Issue by oMaikeru** [letsmokee/ApexXPFarmer#10]
As the title says im still getting some errors ill leave them down here:

Traceback (most recent call last):
  File "ApexFarmer.py", line 371, in <module>
ValueError: invalid literal for int() with base 10: ''
[6364] Failed to execute script 'ApexFarmer' due to unhandled exception!

Traceback (most recent call last):
  File "ApexFarmer.py", line 371, in <module>
ValueError: invalid literal for int() with base 10: ''
[9172] Failed to execute script 'ApexFarmer' due to unhandled exception!

**Comment by letsmokee** [comment]
If you can, test with debug on and when it will happen send last photo that script saves in folder with executable

**Comment by letsmokee** [comment]
Fixed in new release v1.7
