### ISSUE TITLE
Failed to execute script 'ApexFarmer' due to unhandled exception: The system cannot find the file specified

### ISSUE THREAD

**Issue by TheBosoYolo** [letsmokee/ApexXPFarmer#12]
Hello! I installed the tesseract according to the guide, added it to path. Now i can execute it in my command prompt:
```
C:\Users\********\Desktop\ap>tesseract --version
tesseract v5.3.3.20231005
 leptonica-1.83.1
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.4) : libpng 1.6.40 : libtiff 4.6.0 : zlib 1.2.13 : libwebp 1.3.2 : libopenjp2 2.5.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.7.2 zlib/1.3 liblzma/5.4.4 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.5
 Found libcurl/8.3.0 Schannel zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.11.0
 ```
 Now i tried running the bot, but every time i get this error:
 ```
Traceback (most recent call last):
  File "ApexFarmer.py", line 170, in <module>
  File "subprocess.py", line 389, in call
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[19884] Failed to execute script 'ApexFarmer' due to unhandled exception!
```
the wierd thing is line 170 in the ApexFarmer is empty. I did try running it as admin, but to no avail. Can you help me?

**Comment by letsmokee** [comment]
Closed as author is not answering
